name: build
on: [push, pull_request]
jobs:
  gcc-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: gcc -O2 -Wall -std=c11 -o handheld_calc main.c postfix.c findroot.c -lm
